### ISSUE TITLE
Copy for workshop CFP

### ISSUE THREAD

**Issue by DudeWhoCode** [pythonindia/inpycon2019-tasks#43] opened 2019-04-16 08:55 UTC
Write a detailed copy for workshop CFP

**Comment by bravegnu** [comment] 2019-04-16 09:54
Duplicate of #37 ?

**Comment by zerothabhishek** [comment] 2019-04-17 14:29
I'll need the following details for writing the copy -

- How many workshops will happen ?
  6 as 3 tracks
- Duration ?
  2.5 hrs
- How many attendees per workshop ?
- What are the CFP open/close dates ?
  Apr-20 - ?
- What is the format - classical-format (instructor lead) or APAC-format ?
- Who should propose (like trainers or anyone) ? 
- What topics are expected ? 
- Are the proposal sections same that in talks (Core Python, Others, Developer Tools and automation, Networking and Security, Data Science Machine Learning and AI, Embedded Python and IOT, Web development, Culture and society) ?
- What is the review process like ?
- Are there rehearsals ?
- Any best practices ?


@bravegnu @DudeWhoCode

**Comment by bravegnu** [comment] 2019-04-19 03:12
> I'll need the following details for writing the copy -
> 
>     * How many workshops will happen ?
>       6 as 3 tracks

Yes.

> 
>     * Duration ?
>       2.5 hrs

Correct.

> 
>     * How many attendees per workshop ?

The rooms we are planning to book, can accommodate a maximum of 40 attendees. We can also check with the proposer how many people he can accommodate. For example for workshop involving hardware, there might be certain limitations on the no. of hardware boards available, etc.

>     * What are the CFP open/close dates ?
>       Apr-20 - ?

Will check and get back to you on this.

> 
>     * What is the format - classical-format (instructor lead) or APAC-format ?

Classical - Instructor lead format. 

>     * Who should propose (like trainers or anyone) ?

Anyone.

>     * What topics are expected ?

As long as the workshop is hands-on and would be of interest to the Python community, we should be fine with it.

>     * Are the proposal sections same that in talks (Core Python, Others, Developer Tools and automation, Networking and Security, Data Science Machine Learning and AI, Embedded Python and IOT, Web development, Culture and society) ?

Culture and Society can be dropped. The others can be maintained, as such.

>     * What is the review process like ?

A detailed outline, with breakdown to topics and sub-topics, will be required, as part of the proposal. And draft slides for for most of the topics might be required for the review. Ideally, these workshops should have been previously done, as part of a local event.

>     * Are there rehearsals ?

It will be nice to have rehearsals. If not for the entire duration, may be the first 1 hour.

>     * Any best practices ?

As mentioned earlier, it will be good if this is a repeat workshop, rather than the first attempt. So that the issues have been ironed out, and flow has been tuned up.

The workshop should be interspersed with proper hands-on exercises. At the end of the workshop people should be ramped up on the workshop topic, and should be able to take it forward themselves.

**Comment by bravegnu** [comment] 2019-04-19 14:50
>     * What are the CFP open/close dates ?
>       Apr-20 - ?

The selected workshops should be announced atleast by 1st August. This will allow sufficient time for ticket sales. We need to back-work the dates for closing the workshop CFP accordingly.

**Comment by zerothabhishek** [comment] 2019-05-02 03:35
Draft:
```
Workshops are an important part of the PyCon India. Hands on learning is as important as talks for a fulfilling conference experience. Like talks, workshops are also conducted by the members of the Python community. To streamline the selection of topics for the workshops, we use a process similar to the Talks CFP.

Here are some notable points about workshops at PyConIndia 2019:

- Happen on 14-oct 2019 (the third day)
- Venue is: IITM Research Park
- 6 workshops across 3 tracks
- Duration: 2.5 hours
- Upto 40 attendees per workshop

Anyone can propose for conducting a workshop. Any topic of interest to the Python community is okay. To get a sense of the topics from last year, take a look here - https://in.pycon.org/cfp/2018/proposals/

All the facilities needed to conduct the workshop will be provided. This includes plug points, projectors etc. Attendees will be bringing their own laptops.

In the CFP proposal, please mention an outline of the workshop and the prerequisites. And the slides if possible. Also mention if you have conducted the same workshop before.

The workshop should be interspersed with proper hands-on exercises. After the workshop people should be ramped up on the workshop topic, and should be able to take it forward themselves.
```

More questions:
- Is there a remuneration planned for the trainers
- Will volunteers be provided to help the attendees. If so, how many. If not, should the trainer bring her own volunteers


@bravegnu @DudeWhoCode

**Comment by bravegnu** [comment] 2019-05-02 14:27
> Here are some notable points about workshops at PyConIndia 2019:

PyCon India
 
> - Happen on 14-oct 2019 (the third day)

14th Oct

Also include the closing date, and selected workshop announcement date.

> - Venue is: IITM Research Park

Venue is IITM Research Park

> - 6 workshops across 3 tracks
> - Duration: 2.5 hours
> - Upto 40 attendees per workshop
> 
> Anyone can propose for conducting a workshop.

If there is something specific we can mention, otherwise this should be obvious?

> Any topic of interest to the Python community is okay. 

The workshop should help attendees learn a new skill, technology or library.

> All the facilities needed to conduct the workshop will be provided. This includes plug points, projectors etc. Attendees will be bringing their own laptops.
> 
> In the CFP proposal, please mention an outline of the workshop and the prerequisites. And the slides if possible. Also mention if you have conducted the same workshop before.
> 
> The workshop should be interspersed with proper hands-on exercises. After the workshop people should be ramped up on the workshop topic, and should be able to take it forward themselves.
> ```
> 
> More questions:
> 
>     * Is there a remuneration planned for the trainers

This is a nice to have, and is generally based on availability of budget. So while we might end up giving them a honorarium, let's not commit that for now.
 
>     * Will volunteers be provided to help the attendees. If so, how many. If not, should the trainer bring her own volunteers

If the speaker requires volunteers that can be indicated as part of the proposal. 

Also we should indicate that rehearsals will happen before the speaker presents them at the conference.

**Closed as completed** 2019-06-13 09:18 UTC
Labels: cat: cfp
